In [3]:
#importing libraries

import numpy as np
import matplotlib.pyplot as  plt
import cv2
import tensorflow as tf
import os

In [4]:
import pandas as pd

labels = pd.read_csv("eye_gender_data/Training_set.csv")   # loading the labels
file_paths = [[fname, 'eye_gender_data/train/' + fname] for fname in labels['filename']]
images = pd.DataFrame(file_paths, columns=['filename', 'filepaths'])
train_data = pd.merge(images, labels, how = 'inner', on = 'filename')

data = []     # initialize an empty numpy array
image_size = 100      # image size taken is 100 here. one can take other size too
for i in range(len(train_data)):
  
  img_array = cv2.imread(train_data['filepaths'][i], cv2.IMREAD_GRAYSCALE)   # converting the image to gray scale

  new_img_array = cv2.resize(img_array, (image_size, image_size))      # resizing the image array
  data.append(new_img_array)

In [5]:
#convert to an array
data_arr = np.array(data)

In [6]:

print(data_arr.shape, data_arr.dtype)

(9220, 100, 100) uint8


In [7]:
data_arr

array([[[188, 188, 189, ..., 176, 175, 175],
        [189, 189, 188, ..., 174, 173, 172],
        [190, 189, 188, ..., 168, 167, 167],
        ...,
        [133, 137, 144, ..., 168, 167, 166],
        [134, 138, 145, ..., 165, 164, 163],
        [135, 139, 146, ..., 163, 162, 162]],

       [[167, 169, 173, ..., 194, 195, 195],
        [168, 170, 173, ..., 193, 194, 195],
        [171, 171, 173, ..., 192, 193, 194],
        ...,
        [183, 185, 189, ..., 199, 197, 196],
        [183, 186, 189, ..., 199, 197, 195],
        [184, 186, 190, ..., 199, 196, 195]],

       [[181, 179, 177, ..., 131, 134, 136],
        [178, 177, 174, ..., 127, 127, 128],
        [174, 172, 170, ..., 120, 118, 116],
        ...,
        [126, 128, 132, ...,  99,  96,  94],
        [127, 130, 133, ...,  98,  95,  93],
        [128, 131, 135, ...,  98,  94,  92]],

       ...,

       [[189, 190, 192, ..., 142, 144, 145],
        [189, 190, 190, ..., 134, 136, 137],
        [190, 189, 188, ..., 122, 124, 126

In [8]:
#reshaping the data
train_image_reshp =  np.stack([data_arr]*3, axis=-1)

In [9]:
train_image_reshp.shape

(9220, 100, 100, 3)

In [10]:
train_image_reshp.dtype

dtype('uint8')

In [11]:
train_image_reshp

array([[[[188, 188, 188],
         [188, 188, 188],
         [189, 189, 189],
         ...,
         [176, 176, 176],
         [175, 175, 175],
         [175, 175, 175]],

        [[189, 189, 189],
         [189, 189, 189],
         [188, 188, 188],
         ...,
         [174, 174, 174],
         [173, 173, 173],
         [172, 172, 172]],

        [[190, 190, 190],
         [189, 189, 189],
         [188, 188, 188],
         ...,
         [168, 168, 168],
         [167, 167, 167],
         [167, 167, 167]],

        ...,

        [[133, 133, 133],
         [137, 137, 137],
         [144, 144, 144],
         ...,
         [168, 168, 168],
         [167, 167, 167],
         [166, 166, 166]],

        [[134, 134, 134],
         [138, 138, 138],
         [145, 145, 145],
         ...,
         [165, 165, 165],
         [164, 164, 164],
         [163, 163, 163]],

        [[135, 135, 135],
         [139, 139, 139],
         [146, 146, 146],
         ...,
         [163, 163, 163],
        

In [12]:
train_image_reshp.max()

255

In [13]:
#normalizing 

train_image_norm = train_image_reshp/255
train_image_norm

array([[[[0.7372549 , 0.7372549 , 0.7372549 ],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         [0.74117647, 0.74117647, 0.74117647],
         ...,
         [0.69019608, 0.69019608, 0.69019608],
         [0.68627451, 0.68627451, 0.68627451],
         [0.68627451, 0.68627451, 0.68627451]],

        [[0.74117647, 0.74117647, 0.74117647],
         [0.74117647, 0.74117647, 0.74117647],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         ...,
         [0.68235294, 0.68235294, 0.68235294],
         [0.67843137, 0.67843137, 0.67843137],
         [0.6745098 , 0.6745098 , 0.6745098 ]],

        [[0.74509804, 0.74509804, 0.74509804],
         [0.74117647, 0.74117647, 0.74117647],
         [0.7372549 , 0.7372549 , 0.7372549 ],
         ...,
         [0.65882353, 0.65882353, 0.65882353],
         [0.65490196, 0.65490196, 0.65490196],
         [0.65490196, 0.65490196, 0.65490196]],

        ...,

        [[0.52156863, 0.52156863, 0.52156863],
         [0.5372549 , 0.5372549 , 0.5372549 ]

In [14]:
#let's addresss the labels. we'll encode it to have 1 and 0
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_labels = le.fit_transform(train_data[['label']])


C:\Users\kawba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
train_labels

array([1, 0, 0, ..., 1, 1, 0])

In [16]:
train_labels.shape

(9220,)

In [17]:
train_labels.dtype

dtype('int32')

In [18]:
#how to join these two???? #could have appended while still a list,
#  encode the label column and then convert to an array

In [19]:
#model training
#let's try transfer learning using VGG_19

INPUT_SHAPE = (100, 100, 3)
vgg_layers = tf.keras.applications.vgg19.VGG19(weights='imagenet', include_top= False, input_shape=INPUT_SHAPE)

vgg_layers.summary()

Model: "vgg19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 100, 100, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 100, 100, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 100, 100, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 50, 50, 64)        0         
                                                                 
 block2_conv1 (Conv2D)       (None, 50, 50, 128)       73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 50, 50, 128)       147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 25, 25, 128)       0     

In [20]:
#let's make the layers trainable
for layer in vgg_layers.layers:
    layer.trainable = True

for layer in vgg_layers.layers:
    print(layer, layer.trainable )

<keras.engine.input_layer.InputLayer object at 0x0000020847FFAD70> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8CD1030> True
<keras.layers.convolutional.Conv2D object at 0x0000020847FD7040> True
<keras.layers.pooling.MaxPooling2D object at 0x00000208E8CD2650> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8CD1810> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8DEC0D0> True
<keras.layers.pooling.MaxPooling2D object at 0x00000208E8DED150> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8CD36D0> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8DEE5C0> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8DEF5B0> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8DEEA40> True
<keras.layers.pooling.MaxPooling2D object at 0x00000208E8E01510> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8E01090> True
<keras.layers.convolutional.Conv2D object at 0x00000208E8E026E0> True
<keras.layers.conv

In [21]:
#lets attempt a cnn on the vgg model

# define sequential model
model = tf.keras.models.Sequential()

# Add the vgg convolutional base model
model.add(vgg_layers)

# add flatten layer
model.add(tf.keras.layers.Flatten())

# add dense layers with some dropout
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dropout(rate=0.3))
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dropout(rate=0.3))

# add output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# compile model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5), 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

# view model layers
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg19 (Functional)          (None, 3, 3, 512)         20024384  
                                                                 
 flatten (Flatten)           (None, 4608)              0         
                                                                 
 dense (Dense)               (None, 256)               1179904   
                                                                 
 dropout (Dropout)           (None, 256)               0         
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                2

In [22]:
EPOCHS = 100

es_callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=3, 
                                               restore_best_weights=True,
                                               verbose=1)

history = model.fit(train_image_norm, train_labels,
                    batch_size=32,
                    callbacks=[es_callback], 
                    validation_split=0.1, epochs=EPOCHS,
                    verbose=1)

Epoch 1/100
260/260 [==============================] - 1068s 4s/step - loss: 0.4420 - accuracy: 0.8179 - val_loss: 0.1337 - val_accuracy: 0.9490
Epoch 2/100
260/260 [==============================] - 1003s 4s/step - loss: 0.1774 - accuracy: 0.9378 - val_loss: 0.1483 - val_accuracy: 0.9414
Epoch 3/100
260/260 [==============================] - 1006s 4s/step - loss: 0.1332 - accuracy: 0.9522 - val_loss: 0.1153 - val_accuracy: 0.9566
Epoch 4/100
260/260 [==============================] - 3864s 15s/step - loss: 0.1039 - accuracy: 0.9643 - val_loss: 0.1425 - val_accuracy: 0.9425
Epoch 5/100
260/260 [==============================] - 1346s 5s/step - loss: 0.0861 - accuracy: 0.9683 - val_loss: 0.1113 - val_accuracy: 0.9588
Epoch 6/100
 13/260 [>.............................] - ETA: 14:55 - loss: 0.0386 - accuracy: 0.9880

In [ ]:
#let's plot the learning curves
fig, ax = plt.subplots(1, 2, figsize=(10, 4))

history_df = pd.DataFrame(history.history)
history_df[['loss', 'val_loss']].plot(kind='line', ax=ax[0])
history_df[['accuracy', 'val_accuracy']].plot(kind='line', ax=ax[1]);

NameError: name 'plt' is not defined

In [ ]:
# saving the model
save_dir = "/results/"
model_name = 'eye_model.h5'
model.save(model_name)
model_path = save_dir + model_name
print('Saved trained model at %s ' % model_path)

NameError: name 'model' is not defined